server:
   port: 8901
spring:
   application:
      name: backend-emart-oauth2
logging:
  level:
    org:
      springframework:
        security: DEBUG
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false